// Value-only OCCT API. Definitions are generated by CXX; all native ownership stays local.
#pragma once
#include "rust/cxx.h"
namespace confusion { struct ModelStep; struct FaceRequest; struct Mesh; struct ProfileEdge; Mesh evaluate_model(rust::Slice<const ProfileEdge>, rust::Slice<const ModelStep>, rust::Slice<const FaceRequest>); Mesh extrude_region(rust::Slice<const ProfileEdge>, double); struct Point2; struct Mesh; Mesh extrude(rust::Slice<const Point2>, double); }
