// Value-only OCCT API. Definitions are generated by CXX; all native ownership stays local.
#pragma once
#include "rust/cxx.h"
namespace confusion { struct Point2; struct Mesh; Mesh extrude(rust::Slice<const Point2>, double); }
